stages:
  - test #Alle Aufgaben die mit Testen zu tun haben
  - build #Alle Aufgaben die mit Bauen der App zu tun haben

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info


flutter_test:
  stage: test
  script:
    - echo "This job tests something"
    - flutter analyze > $(git branch --show-current)
    - artifacts:
        paths:
          - workflow/flutter-analyze
  tags:
    - dind
image: docker:20.10.16



flutter_build_apk:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - docker build -t fh-wave-builder .
    - flutter build apk
  artifacts:
    paths:
      - build/app/android
  tags:
    - dind



