stages:
  - test #Alle Aufgaben die mit Testen zu tun haben
  - build #Alle Aufgaben die mit Bauen der App zu tun haben

flutter_test:
  stage: test
  script:
    - flutter --version
    - echo "This job tests something"
  tags:
    - flutter

flutter_build_apk:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/android
  tags:
    - flutter

