#stages:
#  - test #Alle Aufgaben die mit Testen zu tun haben
#  - build #Alle Aufgaben die mit Bauen der App zu tun haben
#
#
#variables:
#  DOCKER_TLS_CERTDIR: "/certs"
#
#services:
#  - docker:20.10.16-dind
#
#before_script:
#  - docker info
#
#
#flutter_test:
#  stage: test
#  script:
#    - docker build -t fh-wave-builder .
#    - docker run fh-wave-builder echo "This job tests something"
##    - docker run fh-wave-builder flutter analyze > $(git branch --show-current)
#    - artifacts:
#        paths:
#          - workflow/flutter-analyze
#  tags:
#    - dind
#
#
#
#
##flutter_build_apk:
##  stage: build
##  before_script:
##    - docker run fh-wave-builder flutter packages get
##    - docker run fh-wave-builder flutter clean
##  script:
##    - docker build -t fh-wave-builder .
##    - docker run fh-wave-builder flutter build apk
##  artifacts:
##    paths:
##      - build/app/android
##  tags:
##    - dind



#stages:
#  - test #Alle Aufgaben die mit Testen zu tun haben
#  - build #Alle Aufgaben die mit Bauen der App zu tun haben

#image: docker:20.10.16

#variables:
#  DOCKER_TLS_CERTDIR: "/certs"

#services:
#  - docker:20.10.16-dind

#before_script:
#  - docker info

#flutter_test:
#  stage: test
#  script:
#    - docker build -t fh-wave-builder .
#    - docker run fh-wave-builder echo "This job tests something"
#    - docker run fh-wave-builder flutter analyze .
#  tags:
#    - dind

code_quality:
  stage: test
  image: "cirrusci/flutter:1.22.5"
  before_script:
    - echo "This job tests something"
    - flutter channel stable
    - flutter upgrade
  script:
    - flutter analyze . > analyzes
  artifacts:
    paths:
      - workflow/flutter-analyze



flutter_build_apk:
  stage: build
  image: "cirrusci/flutter:1.22.5"
  before_script:
      - flutter packages get
      - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
        - build/app/android


#test:
#  stage: test
#  image: "cirrusci/flutter:1.22.5"
#  before_script:
#    - pub global activate junitreport
#    - export PATH="$PATH:$HOME/.pub-cache/bin"
#  script:
#    - flutter test --machine --coverage | tojunit -o report.xml
#    - lcov --summary coverage/lcov.info
#    - genhtml coverage/lcov.info --output=coverage
#  coverage: '/lines\.*: \d+\.\d+\%/'
#  artifacts:
#    name: coverage
#    paths:
#      - $CI_PROJECT_DIR/coverage
#    reports:
#      junit: report.xml



# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml



#test:
#  stage: test
#  image: "cirrusci/flutter:1.22.5"
#  before_script:
#    - pub global activate junitreport
#    - export PATH="$PATH:$HOME/.pub-cache/bin"
#  script:
#    - flutter test --machine --coverage | tojunit -o report.xml
#    - lcov --summary coverage/lcov.info
#    - genhtml coverage/lcov.info --output=coverage
#  coverage: '/lines\.*: \d+\.\d+\%/'
#  artifacts:
#    name: coverage
#    paths:
#      - $CI_PROJECT_DIR/coverage
#    reports:
#      junit: report.xml

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production