// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_XXedPHIKqi_ClqDDeA8Irt8_yenGbKg',
    appId: '1:728562690240:web:5626bdd679aaeb4ceba525',
    messagingSenderId: '728562690240',
    projectId: 'fh-wave',
    authDomain: 'fh-wave.firebaseapp.com',
    storageBucket: 'fh-wave.appspot.com',
    measurementId: 'G-CYT906L4PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUV9WeE0Kl-47hzEZwWcRZVreJfotw-A',
    appId: '1:728562690240:android:d1967f8145a42636eba525',
    messagingSenderId: '728562690240',
    projectId: 'fh-wave',
    storageBucket: 'fh-wave.appspot.com',
    databaseURL: "https://fh-wave-default-rtdb.europe-west1.firebasedatabase.app"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3pzJ1ha2BrYgCtBXBAGaXaH5tqDl4tgM',
    appId: '1:728562690240:ios:5fd4131da9380a05eba525',
    messagingSenderId: '728562690240',
    projectId: 'fh-wave',
    storageBucket: 'fh-wave.appspot.com',
    iosClientId: '728562690240-jj733tqquv5k0jai0benfbs99un6anh3.apps.googleusercontent.com',
    iosBundleId: 'de.fhkiel.fhWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3pzJ1ha2BrYgCtBXBAGaXaH5tqDl4tgM',
    appId: '1:728562690240:ios:5fd4131da9380a05eba525',
    messagingSenderId: '728562690240',
    projectId: 'fh-wave',
    storageBucket: 'fh-wave.appspot.com',
    iosClientId: '728562690240-jj733tqquv5k0jai0benfbs99un6anh3.apps.googleusercontent.com',
    iosBundleId: 'de.fhkiel.fhWave',
  );
}
